### ISSUE TITLE
Incompatibility issues with two extensions

### ISSUE THREAD

**Issue by iamdarkle** [v17development/flarum-support-feedback#1]
Hi, I have found two errors that when entering a new ticket cause a graphical error, scrolls the ticket down and doesn't show the avatar of the user, in the console I got this error:

![msedge_vOJZH4Czoy](https://user-images.githubusercontent.com/15818451/143875036-70c45b97-9f46-4116-b8c6-e41d0acbf556.png)

It's related to `fof/gamification`, when I disable gamification this error disappears, but a new one appears:

![msedge_piPrM0HBMI](https://user-images.githubusercontent.com/15818451/143875158-61d0a93e-f8d6-4e64-a8e4-e2a8734c8b16.png)

This is related to `clarkwinkelmann/flarum-ext-circle-groups`, also when deactivating it disappears and no longer appears any error so the ticket is displayed normally.

**Comment by clarkwinkelmann** [comment]
I have silenced the javascript error in version 1.0.1 of https://github.com/clarkwinkelmann/flarum-ext-circle-groups if the user groups are not loaded.

I have not tested with the Support extension and I assume it doesn't really fix compatibility since the error means that an extension (probably Support itself) has loaded the user without its groups relationship.

The Support extension might need to add an `include` for `post(s).user.groups` somewhere to ensure the groups are loaded and available to both the `CommentPost` component and other extensions like Color Circle.

**Comment by jaspervriends** [comment]
Added user groups to the includes in new release :)
